# Generated by Django 4.1.4 on 2023-01-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_asignacion_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarios',
            name='horas_asignadas',
            field=models.ManyToManyField(related_name='horas', to='users.asignacion'),
        ),
    ]
